Module Constants
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const DatabaseFileName = "end.db"
    Friend Const DropAllText = "Drop All"
    Friend Const FightText = "FIGHT!"
    Friend Const InventoryText = "Inventory"
    Friend Const MoveText = "Move..."
    Friend Const NeverMindText = "Never Mind"
    Friend Const NoText = "No"
    Friend Const OkText = "Ok"
    Friend Const QuitText = "Quit"
    Friend Const StartNewGameText = "Start New Game"
    Friend Const StatisticsText = "Statististics"
    Friend Const YesText = "Yes"
End Module
