Public Module Columns
    Public Const CharacterIdColumn = "CharacterId"
    Public Const CharacterNameColumn = "CharacterName"
    Public Const EsteemColumn = "Esteem"
    Public Const FromCharacterIdColumn = "FromCharacterId"
    Public Const FromLocationIdColumn = "FromLocationId"
    Public Const InventoryIdColumn = "InventoryId"
    Public Const ItemIdColumn = "ItemId"
    Public Const ItemTypeIdColumn = "ItemTypeId"
    Public Const ItemTypeNameColumn = "ItemTypeName"
    Public Const LocationIdColumn = "LocationId"
    Public Const LocationNameColumn = "LocationName"
    Public Const PlayerIdColumn = "PlayerId"
    Public Const RouteIdColumn = "RouteId"
    Public Const RouteNameColumn = "RouteName"
    Public Const StartLocationIdColumn = "StartLocationId"
    Public Const StatisticTypeIdColumn = "StatisticTypeId"
    Public Const StatisticValueColumn = "StatisticValue"
    Public Const ToCharacterIdColumn = "ToCharacterId"
    Public Const ToLocationIdColumn = "ToLocationId"
    Public Const UseEventNameColumn = "UseEventName"
    Public Const WorldIdColumn = "WorldId"
End Module
