Public Module Tables
    Public Const Characters = "Characters"
    Public Const CharacterEquippedItems = "CharacterEquippedItems"
    Public Const CharacterStatistics = "CharacterStatistics"
    Public Const EquipSlots = "EquipSlots"
    Public Const Inventories = "Inventories"
    Public Const InventoryItems = "InventoryItems"
    Public Const Items = "Items"
    Public Const ItemTypeEquipSlots = "ItemTypeEquipSlots"
    Public Const ItemTypes = "ItemTypes"
    Public Const Locations = "Locations"
    Public Const Players = "Players"
    Public Const Routes = "Routes"
    Public Const RouteTypes = "RouteTypes"
    Public Const Worlds = "Worlds"
End Module
